pipeline {
    // agent any
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('Init') {
            steps {
                script { 
                   withAWS(region:'us-west-2',credentials:'aws-creds') {
                        sh """ 
                            cd 25-acm
                            terraform init
                        """ 
                   }    
                }   
            }
        }
        stage('Plan') {
            steps {
                script { 
                  withAWS(region:'us-west-2',credentials:'aws-creds') {   
                    sh """ 
                        cd 25-acm
                        terraform plan
                    """ 
                  }    
                }
            }
        }
        stage('Deploy') {
            steps {
                script { 
                  withAWS(region:'us-west-2',credentials:'aws-creds') {   
                    sh """ 
                        cd 25-acm
                        terraform apply -auto-approve
                    """ 
                   } 
                }
            }
        }
    }
    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failures'
        }
    }
}